Repository hulu/roca, pull requests merged in 2020-07, with the labels that each got.

#27 fix(docs): Clarify installation, test location, and entrypoint requirements
  README.md
  docs/README.md
Labels: bug, enhancement

#28 Allow a test file to return multiple suite objects
  package-lock.json
  package.json
  resources/roca_main.brs
Labels: enhancement

#31 fix(lib): bail after brs throws exception
  resources/roca_main.brs
  resources/tap.brs
Labels: bug

#30 feat(doc): add table of contents to README
  README.md
Labels: enhancement

#33 chore(toc): Add precommit hook for doctoc
  README.md
  package-lock.json
  package.json
Labels: dependencies, enhancement

#29 feat(api): Allow passing fields to cases
  README.md
  resources/roca_lib.brs
Labels: enhancement
