Repository hulu/roca, pull requests merged in 2021-04, with the labels that each got.

#82 chore(docs): update mockFunction API documentation
  docs/api/reference/mocks.md
  docs/guides/testing-functions.md
Labels: documentation, enhancement

#86 fix(reporter): don't double-count tests
  src/reporter/JestReporter.ts
Labels: bug

#87 Issue #34 Add isValid assertion
  docs/api/reference/asserts.md
  resources/assert_lib.brs
Labels: documentation, enhancement

#92 chore(test): put e2e tests in a separate folder
  test/README.md
  test/e2e/before-after/after-each/tests/01-nested.test.brs
  test/e2e/before-after/after-each/tests/02-single-level.test.brs
  test/e2e/before-after/after-each/tests/03-multiple-calls.test.brs
  test/e2e/before-after/after-each/tests/04-order.test.brs
  test/e2e/before-after/before-after.test.js
  test/e2e/before-after/before-each/tests/01-nested.test.brs
  test/e2e/before-after/before-each/tests/02-single-level.test.brs
  test/e2e/before-after/before-each/tests/03-multiple-calls.test.brs
  test/e2e/before-after/before-each/tests/04-order.test.brs
  test/e2e/before-after/mixed/tests/01-nested.test.brs
  test/e2e/before-after/mixed/tests/02-single-level.test.brs
  test/e2e/parameterized/fit_each/tests/01-fit_each.test.brs
  test/e2e/parameterized/it_each/tests/01-it_each.test.brs
  test/e2e/parameterized/parameterized.test.js
  test/e2e/parameterized/xit_each/tests/01-xit_each.test.brs
  test/e2e/selection/fdescribe/tests/fdescribe.test.brs
  test/e2e/selection/fit/tests/excluded.test.brs
  test/e2e/selection/fit/tests/fit.test.brs
  test/e2e/selection/mixed/tests/mixed.test.brs
  test/e2e/selection/selection.test.js
  test/e2e/selection/xdescribe/tests/xdescribe.test.brs
  test/e2e/selection/xit/tests/unmodified.test.brs
  test/e2e/selection/xit/tests/xit.test.brs
  test/e2e/simple-suites/multiple-files/tests/bar.test.brs
  test/e2e/simple-suites/multiple-files/tests/foo.test.brs
  test/e2e/simple-suites/nested/tests/nested.test.brs
  test/e2e/simple-suites/no-cases/tests/no-cases.test.brs
  test/e2e/simple-suites/simple-suites.test.js
  test/e2e/simple-suites/single-level/tests/single-level.test.brs
  test/e2e/util.js
Labels: enhancement

#91 feat(cli): support testing specific files
  bin/cli.js
  docs/api/cli-options.md
  docs/getting-started/quick-start.md
  package-lock.json
  package.json
  src/index.ts
  src/util.ts
  test/e2e/util.js
  test/runner/file-match.test.ts
  test/runner/resources/bar/bar-suffix.test.brs
  test/runner/resources/bar/bar.test.brs
  test/runner/resources/bar/prefix-bar.test.brs
  test/runner/resources/fly-you-fools.test.brs
  test/runner/resources/foo/main.test.brs
  test/runner/resources/foo2/main.test.brs
  test/runner/resources/no-test-ext.brs
Labels: dependencies, enhancement

#93 chore(infra): convert to yarn instead of npm
  .github/workflows/pull-request.yaml
  README.md
  package-lock.json
  test/README.md
  yarn.lock
Labels: dependencies, documentation, enhancement

#95 fix(runner): return correct exit code when something fails
  src/index.ts
  src/reporter/JestReporter.ts
  src/runner/JestRunner.ts
Labels: bug

#96 chore(infra): update brs to latest version
  package.json
  yarn.lock
Labels: dependencies
